sklearn code implementation

1. Standard KMeans (Randomly initialized)

In [1]:
from sklearn.cluster import KMeans
import numpy as np

X = np.random.rand(200, 2)

# Ordinary KMeans: Random initialization
kmeans_rand = KMeans(n_clusters=3, init='random', n_init=10)
labels_rand = kmeans_rand.fit_predict(X)

In [2]:
print(labels_rand)

[1 0 0 2 2 2 0 2 1 2 2 0 0 2 2 2 2 1 2 2 1 1 2 2 1 1 2 0 2 2 0 2 1 2 1 0 0
 2 0 2 2 0 1 1 2 0 0 2 1 0 2 0 2 1 2 0 1 0 0 2 0 0 1 0 2 1 2 0 1 2 0 1 1 0
 2 2 1 0 1 2 1 2 2 1 1 1 1 1 0 0 1 0 0 1 2 0 2 1 1 1 0 0 1 1 2 2 1 2 1 2 0
 1 1 1 1 1 1 0 1 2 0 0 0 1 0 1 2 2 0 2 0 1 0 1 1 0 0 2 0 2 2 0 2 2 2 1 0 0
 1 1 2 2 2 1 2 2 0 2 2 1 1 0 1 0 1 0 2 2 0 2 0 2 1 1 1 0 0 2 2 2 2 0 2 2 1
 2 2 2 0 2 1 2 2 2 0 2 1 2 0 0]


In [3]:
print(X)

[[0.13521113 0.78297952]
 [0.57626336 0.25832905]
 [0.66055584 0.27342036]
 [0.54942766 0.51770121]
 [0.72035617 0.54251595]
 [0.724206   0.62469959]
 [0.76386527 0.38763931]
 [0.72949824 0.58796051]
 [0.10835412 0.73817837]
 [0.72263792 0.66070144]
 [0.36062615 0.98602823]
 [0.83897751 0.13105615]
 [0.77415457 0.22248819]
 [0.3543815  0.98855264]
 [0.73773037 0.96767902]
 [0.63354706 0.73753181]
 [0.48395665 0.97802235]
 [0.43209838 0.45171074]
 [0.71364036 0.9370034 ]
 [0.31222556 0.77532892]
 [0.20906531 0.45197415]
 [0.14916659 0.52867358]
 [0.80276921 0.64667562]
 [0.17709182 0.92521578]
 [0.2783072  0.67526706]
 [0.3165357  0.02333803]
 [0.15314953 0.96723262]
 [0.81386809 0.02648433]
 [0.76482659 0.68369798]
 [0.96791163 0.91467009]
 [0.5604841  0.28104899]
 [0.26991651 0.74166533]
 [0.19189788 0.43078637]
 [0.60004117 0.84836104]
 [0.10664382 0.3662511 ]
 [0.69433739 0.32774512]
 [0.46958136 0.20213099]
 [0.37243966 0.99763005]
 [0.46999292 0.03562058]
 [0.37520372 0.9998316 ]


2. K-Means++（default）

In [4]:
# default  init='k-means++'
kmeans_pp = KMeans(n_clusters=3, init='k-means++', n_init=10)
labels_pp = kmeans_pp.fit_predict(X)

In [5]:
print(labels_rand)

[1 0 0 2 2 2 0 2 1 2 2 0 0 2 2 2 2 1 2 2 1 1 2 2 1 1 2 0 2 2 0 2 1 2 1 0 0
 2 0 2 2 0 1 1 2 0 0 2 1 0 2 0 2 1 2 0 1 0 0 2 0 0 1 0 2 1 2 0 1 2 0 1 1 0
 2 2 1 0 1 2 1 2 2 1 1 1 1 1 0 0 1 0 0 1 2 0 2 1 1 1 0 0 1 1 2 2 1 2 1 2 0
 1 1 1 1 1 1 0 1 2 0 0 0 1 0 1 2 2 0 2 0 1 0 1 1 0 0 2 0 2 2 0 2 2 2 1 0 0
 1 1 2 2 2 1 2 2 0 2 2 1 1 0 1 0 1 0 2 2 0 2 0 2 1 1 1 0 0 2 2 2 2 0 2 2 1
 2 2 2 0 2 1 2 2 2 0 2 1 2 0 0]


In [6]:
print(X)

[[0.13521113 0.78297952]
 [0.57626336 0.25832905]
 [0.66055584 0.27342036]
 [0.54942766 0.51770121]
 [0.72035617 0.54251595]
 [0.724206   0.62469959]
 [0.76386527 0.38763931]
 [0.72949824 0.58796051]
 [0.10835412 0.73817837]
 [0.72263792 0.66070144]
 [0.36062615 0.98602823]
 [0.83897751 0.13105615]
 [0.77415457 0.22248819]
 [0.3543815  0.98855264]
 [0.73773037 0.96767902]
 [0.63354706 0.73753181]
 [0.48395665 0.97802235]
 [0.43209838 0.45171074]
 [0.71364036 0.9370034 ]
 [0.31222556 0.77532892]
 [0.20906531 0.45197415]
 [0.14916659 0.52867358]
 [0.80276921 0.64667562]
 [0.17709182 0.92521578]
 [0.2783072  0.67526706]
 [0.3165357  0.02333803]
 [0.15314953 0.96723262]
 [0.81386809 0.02648433]
 [0.76482659 0.68369798]
 [0.96791163 0.91467009]
 [0.5604841  0.28104899]
 [0.26991651 0.74166533]
 [0.19189788 0.43078637]
 [0.60004117 0.84836104]
 [0.10664382 0.3662511 ]
 [0.69433739 0.32774512]
 [0.46958136 0.20213099]
 [0.37243966 0.99763005]
 [0.46999292 0.03562058]
 [0.37520372 0.9998316 ]


3. K-Means-- Simple handwritten Implementation (Core Logic)

In [7]:
def kmeans_minus_minus(X, k):
    n_samples = X.shape[0]
    # All the initial points are centered
    centers = X.copy()
    
    # Gradually delete until only k centers remain
    while len(centers) > k:
        # Calculate the distance between each pair and find the one that is closest
        dist_mat = np.linalg.norm(centers[:, None] - centers, axis=2)
        # Excluding its own distance of 0
        np.fill_diagonal(dist_mat, np.inf)
        # Find the nearest point and delete it
        idx_to_del = np.argmin(np.min(dist_mat, axis=1))
        centers = np.delete(centers, idx_to_del, axis=0)
    
    # Find the nearest point and delete it
    km = KMeans(n_clusters=k, init=centers, n_init=1)
    return km.fit_predict(X), centers

In [8]:
labels_minus_minus, centers =  kmeans_minus_minus (X, k=3)

In [9]:
print(labels_minus_minus)

[1 2 2 0 0 0 2 0 1 0 1 2 2 1 0 0 0 1 0 1 1 1 0 1 1 2 1 2 0 0 2 1 1 0 1 2 2
 1 2 1 0 2 1 2 0 2 2 1 1 2 1 2 0 2 0 0 1 0 0 0 2 2 2 2 0 2 0 2 2 0 2 2 1 0
 0 0 2 2 1 0 1 0 1 1 2 2 1 1 2 2 1 2 2 2 0 2 0 2 2 1 0 2 1 2 0 0 2 1 1 0 2
 2 2 1 2 1 2 2 1 0 2 2 2 1 2 2 0 0 2 1 2 1 0 1 2 2 2 0 2 0 1 0 0 0 0 1 0 2
 1 2 1 0 0 1 0 1 0 1 0 1 1 2 2 2 1 2 0 0 0 0 2 1 2 2 1 2 2 0 0 0 0 2 1 0 1
 0 0 0 2 0 1 0 1 1 2 1 1 1 2 2]


In [10]:
print(centers)

[[0.68258271 0.8901633 ]
 [0.14745325 0.89397944]
 [0.50524054 0.35584786]]


K—means— —, How is this function called?

Let's start with the key points:
The official sklearn does not have a built-in KMeans function. It cannot be directly imported from sklearn. You can only implement it by hand and encapsulate it into a directly callable function, which can be used just like calling a library function.
Here's the complete KMeans that can be directly copied and run - encapsulated functions + call examples + comparison with sklearn KMeans.

I. Complete KMeans- Encapsulated Code (Directly callable)

In [11]:
import numpy as np
from sklearn.cluster import KMeans

class KMeansMinusMinus:
    def __init__(self, n_clusters):
        self.k = n_clusters
        self.labels_ = None
        self.cluster_centers_ = None

    def fit_predict(self, X):
        n_samples = X.shape[0]
        # 1. Complete KMeans- Encapsulated Code (Directly callable)
        centers = X.copy()
        
        # 2. Keep deleting the nearest center points until there are only k left
        while len(centers) > self.k:
            # Calculate the pairwise distance matrix
            dist_mat = np.linalg.norm(centers[:, np.newaxis] - centers, axis=2)
            # Set the self-distance to infinity
            np.fill_diagonal(dist_mat, np.inf)
            # Find the point closest to others and delete it
            min_dist_each = np.min(dist_mat, axis=1)
            del_idx = np.argmin(min_dist_each)
            centers = np.delete(centers, del_idx, axis=0)
        
        # 3. Find the point closest to others and delete it
        km = KMeans(n_clusters=self.k, init=centers, n_init=1)
        self.labels_ = km.fit_predict(X)
        self.cluster_centers_ = km.cluster_centers_
        return self.labels_

II. How to Invoke (Exactly the Same usage as sklearn)

In [13]:
# Create test data
X = np.random.rand(200, 2)

# Call KMeans- just like calling sklearn
kmm = KMeansMinusMinus(n_clusters=3)
y_pred = kmm.fit_predict(X)

# Call KMeans- just like calling sklearn
print("tag clustering：", y_pred)
print("center of clustering：\n", kmm.cluster_centers_)

tag clustering： [1 2 1 0 0 0 0 1 2 2 0 2 1 2 0 0 1 1 1 1 2 0 1 1 1 0 1 0 1 2 0 2 0 0 0 1 2
 0 2 2 0 0 1 0 2 2 2 2 0 2 0 0 0 2 2 0 0 1 1 1 2 1 1 0 2 2 0 2 2 0 1 0 1 2
 0 1 1 2 2 1 1 2 1 1 2 0 2 0 0 2 0 2 1 1 0 1 2 1 0 0 1 0 0 2 2 0 1 0 0 0 2
 1 2 1 1 1 0 2 0 2 0 0 2 0 2 0 0 0 0 1 2 0 1 0 1 1 0 2 1 2 2 2 1 2 2 2 2 0
 1 2 0 2 1 0 1 2 1 1 2 2 1 1 2 0 0 0 0 2 1 0 1 1 0 0 1 2 1 2 0 0 0 2 0 0 0
 0 0 0 1 1 1 0 2 0 0 0 2 0 0 2]
center of clustering：
 [[0.4084219  0.22343064]
 [0.32215069 0.72782959]
 [0.81539701 0.6217494 ]]


III. Comparison of Three Writing Methods (Understood at a Glance)

In [15]:
# 1. Random initialization of ordinary KMeans
from sklearn.cluster import KMeans
km_rand = KMeans(n_clusters=3, init="random")
y1 = km_rand.fit_predict(X)

# 2. KMeans++（default）
km_pp = KMeans(n_clusters=3)
y2 = km_pp.fit_predict(X)

# 3. KMeans-- Custom call
km_mm = KMeansMinusMinus(n_clusters=3)
y3 = km_mm.fit_predict(X)

/home/wangkongqiang/miniconda3/envs/Data_Augmentation/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/home/wangkongqiang/miniconda3/envs/Data_Augmentation/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [16]:
print(y1)

[1 0 0 1 1 1 1 0 2 0 1 2 0 2 1 1 0 1 0 0 0 2 1 1 1 1 0 2 0 2 2 0 1 1 1 0 0
 2 2 0 2 2 0 2 0 0 2 2 2 0 1 2 2 2 2 1 2 1 0 0 2 0 0 1 0 2 1 0 0 1 0 2 0 0
 1 1 0 0 0 0 0 0 0 0 0 1 2 1 2 0 1 0 0 1 1 0 0 0 2 1 1 1 1 2 0 1 1 1 1 2 0
 1 0 0 0 0 1 2 1 0 2 1 2 2 0 1 1 1 2 1 2 1 0 1 1 1 1 0 0 0 2 0 1 0 0 0 0 2
 1 0 1 0 1 1 1 0 0 0 2 0 0 0 0 2 2 1 1 0 0 2 0 1 2 1 1 0 0 0 2 2 1 2 2 2 1
 2 2 1 1 1 0 2 0 2 1 2 2 1 2 0]


In [17]:
print(y2)

[2 1 1 2 2 2 2 1 0 1 2 0 1 0 2 2 1 2 1 1 1 0 2 2 2 2 1 0 1 0 0 1 2 2 2 1 1
 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 2 0 2 1 1 0 1 1 2 1 0 2 1 1 2 1 0 1 1
 2 2 1 1 1 1 1 1 1 1 1 2 0 2 0 1 2 1 1 2 2 1 1 1 0 2 2 0 2 0 1 2 2 2 2 0 1
 2 1 1 1 1 2 0 2 1 0 2 0 0 1 2 2 2 0 2 0 2 1 2 2 2 2 1 1 1 0 1 2 1 1 1 1 0
 2 1 2 1 2 2 2 1 1 1 0 1 1 1 1 0 0 2 2 1 1 0 1 2 0 2 2 1 1 1 0 0 2 0 0 0 0
 0 0 2 2 2 1 0 1 0 2 0 0 2 0 1]


In [18]:
print(y3)

[1 2 1 0 0 0 0 1 2 2 0 2 1 2 0 0 1 1 1 1 2 0 1 1 1 0 1 0 1 2 0 2 0 0 0 1 2
 0 2 2 0 0 1 0 2 2 2 2 0 2 0 0 0 2 2 0 0 1 1 1 2 1 1 0 2 2 0 2 2 0 1 0 1 2
 0 1 1 2 2 1 1 2 1 1 2 0 2 0 0 2 0 2 1 1 0 1 2 1 0 0 1 0 0 2 2 0 1 0 0 0 2
 1 2 1 1 1 0 2 0 2 0 0 2 0 2 0 0 0 0 1 2 0 1 0 1 1 0 2 1 2 2 2 1 2 2 2 2 0
 1 2 0 2 1 0 1 2 1 1 2 2 1 1 2 0 0 0 0 2 1 0 1 1 0 0 1 2 1 2 0 0 0 2 0 0 0
 0 0 0 1 1 1 0 2 0 0 0 2 0 0 2]


IV. Key Explanations
1. There are no ready-made library functions, so you have to encapsulate them yourself. Just copy the code above and it can be used.
2. Fully replicate the syntax of sklearn: __init__ set the number of clusters, fit_predict training + prediction;
3. Principle: First, take all the centers → Iterate and delete the most recent redundant centers → When only k centers remain, then iterate through standard KMeans.
4. It is suitable for small samples, but it will be slow for large data volumes (a full-distance matrix needs to be calculated).
I can provide you with another set of visualization codes for the three types of clustering results. Run it to directly view the differences in clustering distribution among the three algorithms. Do you want it?

No